name: C/C++ CI

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    # Run on an older Ubuntu to make flatpack happy
    runs-on: ubuntu-16.04

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Set qtdir
      run: echo ::set-env name=QTDIR::$(Qt5_Dir)
    - name: build linux
      run: ./dist_linux.sh
      #working-directory: firmware
    - name: Save artificat
      uses: actions/upload-artifact@v1
      with:
        name: PatternPaint.AppImage
        path: build-dist-linux/*.AppImage
